# Generated by Django 5.2.5 on 2025-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
