# Generated by Django 5.2.5 on 2025-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_finalquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalquestion',
            name='question_text',
            field=models.TextField(),
        ),
    ]
