# Generated by Django 5.2.5 on 2025-11-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_finalquestion_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_percentages', models.JSONField()),
                ('average_percentage', models.FloatField()),
                ('remark', models.CharField(max_length=10)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('review_data', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
