# Generated by Django 5.2.5 on 2025-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_finalresulthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresulthistory',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
