# Generated by Django 5.2.7 on 2025-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_finalresulthistory_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresulthistory',
            name='attempted_questions',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalresulthistory',
            name='total_questions',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
