# Generated by Django 5.2.7 on 2026-01-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_finalresulthistory_attempted_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, default='Na', max_length=100, null=True),
        ),
    ]
